import{a as l,i as L}from"./assets/vendor-weOZHO9C.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const v="https://furniture-store-v2.b.goit.study/api",m=8,p={CATEGORIES:"categories",FURNITURES:"furnitures",ORDERS:"orders",FEEDBACKS:"feedbacks"},C=()=>{const e=document.querySelector(".furniture-categories-list-item");e&&e.classList.add("current-category")};l.defaults.baseURL=v;let y=1;const T=()=>y+=1,b=()=>y,P=async()=>{const{data:e}=await l(`${p.CATEGORIES}`);return e},u=async(e=1,r=null)=>{const{data:s}=await l(`${p.FURNITURES}`,{params:{limit:m,page:e,category:r}});return s},w="/Project-CreativeTeam02/assets/1all_products-MNNrO4G5.jpg",S="/Project-CreativeTeam02/assets/7kitchens-B1U2sumV.jpg",E="/Project-CreativeTeam02/assets/10furniture_hallway-SzlnEjvC.jpg",I="/Project-CreativeTeam02/assets/12garden_furnitures-BsCHdeVT.jpg",B="/Project-CreativeTeam02/assets/5tables-DczJP-_Y.jpg",$="/Project-CreativeTeam02/assets/2sofas-CtxhA9kI.jpg",k="/Project-CreativeTeam02/assets/8child_furniture-DHKm76Ju.jpg",R="/Project-CreativeTeam02/assets/13accessoires-BnjU54Dx.jpg",O="/Project-CreativeTeam02/assets/11furniture_washrooms-tNgqFRxh.jpg",_="/Project-CreativeTeam02/assets/9office_furnitures-BLI04jhG.jpg",A="/Project-CreativeTeam02/assets/3wardrobe-BspX3wmj.jpg",N="/Project-CreativeTeam02/assets/4beds-D6hwExXz.jpg",q="/Project-CreativeTeam02/assets/6chairs-3pofB28T.jpg",o={categoryList:document.querySelector(".furniture-categories-list"),furnitureList:document.querySelector(".furniture-list"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".button-load-more-furnitures")},g={all:w,"66504a50a1b2c3d4e5f6a7bd":S,"66504a50a1b2c3d4e5f6a7c0":E,"66504a50a1b2c3d4e5f6a7c2":I,"66504a50a1b2c3d4e5f6a7bb":B,"66504a50a1b2c3d4e5f6a7b8":$,"66504a50a1b2c3d4e5f6a7be":k,"66504a50a1b2c3d4e5f6a7c3":R,"66504a50a1b2c3d4e5f6a7c1":O,"66504a50a1b2c3d4e5f6a7bf":_,"66504a50a1b2c3d4e5f6a7b9":A,"66504a50a1b2c3d4e5f6a7ba":N,"66504a50a1b2c3d4e5f6a7bc":q};o.loader.classList.add("visually-hidden");const x=e=>{const r=e.map(s=>typeof s=="string"?`
          <li class="furniture-categories-list-item" style="background-image: url('${g.all}')">
            <span class="category-name">${s}</span>
          </li>
        `:`
        <li class="furniture-categories-list-item" style="background-image: url('${g[s._id]}')" data-id="${s._id}">
          <p class="category-name">${s.name}</p>
        </li>
      `).join("");o.categoryList.innerHTML=r},d=e=>e.furnitures.map(r=>{const s=r.images[0],t=r.color.map(a=>`
          <label class="color-checkbox" style="--color: ${a}">
            <input type="radio" name="color-${r._id}" value="${a}" style="accent-color: ${a}" />
            <span class="color-box"></span>
          </label>
        `).join("");return`
        <li class="product-card">
          <img src="${s}" alt="${r.name}" class="furniture-card-img"/>
          <p class="furniture-name">${r.name}</p>
          <div class="color-options">${t}</div>
          <p class="furniture-price">${r.price} грн</p>
          <button type="button" class="button button-furnitures-detail">Детальніше</button>
        </li>
      `}).join(""),M=e=>{if(!o.furnitureList)return;const r=d({furnitures:e});o.furnitureList.insertAdjacentHTML("beforeend",r)},f=()=>{o.loader.classList.remove("visually-hidden")},n=()=>{o.loader.classList.add("visually-hidden")},h=()=>{o.loadButton.classList.remove("visually-hidden")},H=async()=>{f();try{const e=await P();x(["Всі товари",...e]),C()}catch(e){console.log(e)}n()},U=async()=>{f();try{const e=await u(b()),r=d(e);o.furnitureList.insertAdjacentHTML("beforeend",r)}catch(e){console.log(e)}n(),h()};let j=null;H();U();o.loadButton.addEventListener("click",async()=>{const e=b()+1;try{f();const s=await u(e,j),c=s.totalItems,t=Math.ceil(c/m);if(e>t)return o.loadButton.classList.add("visually-hidden"),n(),L.error({position:"topRight",message:"Sorry there are no more products"});T(),M(s.furnitures),n()}catch(s){console.error(s)}const r=document.querySelector(".furniture-categories-list-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*4,behavior:"smooth"})}});const D=async e=>{const r=e.target.closest(".furniture-categories-list-item");if(!r)return;document.querySelectorAll(".furniture-categories-list-item").forEach(t=>t.classList.remove("current-category")),r.classList.add("current-category");const s=e.target.closest("[data-id]");let c=null;s&&(c=s.dataset.id),j=c;try{const t=await u(1,c);o.furnitureList.innerHTML="";const a=d(t);o.furnitureList.insertAdjacentHTML("beforeend",a),h()}catch(t){console.log(t)}};o.categoryList.addEventListener("click",D);
//# sourceMappingURL=index.js.map
