import{a as l,A as L,i as v}from"./assets/vendor-BtZwNgFY.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const C="https://furniture-store-v2.b.goit.study/api",m=8,p={CATEGORIES:"categories",FURNITURES:"furnitures",ORDERS:"orders",FEEDBACKS:"feedbacks"},T=()=>{const e=document.querySelector(".furniture-categories-list-item");e&&e.classList.add("current-category")};l.defaults.baseURL=C;let y=1;const P=()=>y+=1,b=()=>y,w=async()=>{const{data:e}=await l(`${p.CATEGORIES}`);return e},u=async(e=1,r=null)=>{const{data:s}=await l(`${p.FURNITURES}`,{params:{limit:m,page:e,category:r}});return console.log(s),s},S="/Project-CreativeTeam02/assets/1all_products-MNNrO4G5.jpg",E="/Project-CreativeTeam02/assets/7kitchens-B1U2sumV.jpg",I="/Project-CreativeTeam02/assets/10furniture_hallway-SzlnEjvC.jpg",B="/Project-CreativeTeam02/assets/12garden_furnitures-BsCHdeVT.jpg",$="/Project-CreativeTeam02/assets/5tables-DczJP-_Y.jpg",k="/Project-CreativeTeam02/assets/2sofas-CtxhA9kI.jpg",A="/Project-CreativeTeam02/assets/8child_furniture-DHKm76Ju.jpg",R="/Project-CreativeTeam02/assets/13accessoires-BnjU54Dx.jpg",q="/Project-CreativeTeam02/assets/11furniture_washrooms-tNgqFRxh.jpg",O="/Project-CreativeTeam02/assets/9office_furnitures-BLI04jhG.jpg",_="/Project-CreativeTeam02/assets/3wardrobe-BspX3wmj.jpg",M="/Project-CreativeTeam02/assets/4beds-D6hwExXz.jpg",N="/Project-CreativeTeam02/assets/6chairs-3pofB28T.jpg",a={categoryList:document.querySelector(".furniture-categories-list"),furnitureList:document.querySelector(".furniture-list"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".button-load-more-furnitures")},g={all:S,"66504a50a1b2c3d4e5f6a7bd":E,"66504a50a1b2c3d4e5f6a7c0":I,"66504a50a1b2c3d4e5f6a7c2":B,"66504a50a1b2c3d4e5f6a7bb":$,"66504a50a1b2c3d4e5f6a7b8":k,"66504a50a1b2c3d4e5f6a7be":A,"66504a50a1b2c3d4e5f6a7c3":R,"66504a50a1b2c3d4e5f6a7c1":q,"66504a50a1b2c3d4e5f6a7bf":O,"66504a50a1b2c3d4e5f6a7b9":_,"66504a50a1b2c3d4e5f6a7ba":M,"66504a50a1b2c3d4e5f6a7bc":N};a.loader.classList.add("visually-hidden");const x=e=>{const r=e.map(s=>typeof s=="string"?`
          <li class="furniture-categories-list-item" style="background-image: url('${g.all}')">
            <span class="category-name">${s}</span>
          </li>
        `:`
        <li class="furniture-categories-list-item" style="background-image: url('${g[s._id]}')" data-id="${s._id}">
          <p class="category-name">${s.name}</p>
        </li>
      `).join("");a.categoryList.innerHTML=r},d=e=>e.furnitures.map(r=>{const s=r.images[0],t=r.color.map(o=>`
          <label class="color-checkbox" style="--color: ${o}">
            <input type="radio" name="color-${r._id}" value="${o}" style="accent-color: ${o}" />
            <span class="color-box"></span>
          </label>
        `).join("");return`
        <li class="product-card">
          <img src="${s}" alt="${r.name}" class="furniture-card-img" loading="lazy" decoding="async"/>
          <p class="furniture-name">${r.name}</p>
          <div class="color-options">${t}</div>
          <p class="furniture-price">${r.price} грн</p>
          <button type="button" class="button button-furnitures-detail">Детальніше</button>
        </li>
      `}).join(""),F=e=>{if(!a.furnitureList)return;const r=d({furnitures:e});a.furnitureList.insertAdjacentHTML("beforeend",r)},f=()=>{a.loader.classList.remove("visually-hidden")},n=()=>{a.loader.classList.add("visually-hidden")},h=()=>{a.loadButton.classList.remove("visually-hidden")};function H(){const e=document.querySelector(".accordion-container");e&&new L(e,{duration:300,showMultiple:!1})}const U=async()=>{f();try{const e=await w();x(["Всі товари",...e]),T()}catch(e){console.log(e)}n()},D=async()=>{f();try{const e=await u(b()),r=d(e);a.furnitureList.insertAdjacentHTML("beforeend",r)}catch(e){console.log(e)}n(),h()};let j=null;U();D();a.loadButton.addEventListener("click",async()=>{const e=b()+1;try{f();const s=await u(e,j),c=s.totalItems,t=Math.ceil(c/m);if(e>t)return a.loadButton.classList.add("visually-hidden"),n(),v.error({position:"topRight",message:"Sorry there are no more products"});P(),F(s.furnitures),n()}catch(s){console.error(s)}const r=document.querySelector(".furniture-categories-list-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*4,behavior:"smooth"})}});const z=async e=>{const r=e.target.closest(".furniture-categories-list-item");if(!r)return;document.querySelectorAll(".furniture-categories-list-item").forEach(t=>t.classList.remove("current-category")),r.classList.add("current-category");const s=e.target.closest("[data-id]");let c=null;s&&(c=s.dataset.id),j=c;try{const t=await u(1,c);a.furnitureList.innerHTML="";const o=d(t);a.furnitureList.insertAdjacentHTML("beforeend",o),h()}catch(t){console.log(t)}};a.categoryList.addEventListener("click",z);H();
//# sourceMappingURL=index.js.map
